---
- name: Installing a Apache
  hosts: webservers
  become: true
  tasks:
      - name: Installing package "httpd"
        yum:
           name: httpd
           state: installed
        when: ansible_os_family == "RedHat"

      - name: Start service httpd
        service:
             name: ht---
             state: started
        when: ansible_os_family == "RedHat"
        ignore_errors: yes

      - name: Installing package "apache2"
        apt:
           name: apache2
           state: present
        when: ansible_os_family == "Debian"

      - name: Start service apache2
        service:
             name: apache2
             state: started
        when: ansible_os_family == "Debian"

      - name: Copy index
        copy:
             src: /home/ansadmin/index.html
             dest: /home/ansadmin
             mode: 0777

