---
- name: Installing multiple packages
  hosts: webservers
  become: true
  tasks:
      - name: Installing multiple packages
        yum:
           name: ['git', 'make', 'docker', 'tree', 'mysql', 'gcc']
           state: installed

